apiVersion: v1
kind: Service
metadata:
  name: gg-srv-service
spec:
  selector:
    app: gridgain
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10800
      targetPort: 10800
      name: p10800
    - protocol: TCP
      port: 11211
      targetPort: 11211
      name: p11211
    - protocol: TCP
      port: 47500
      targetPort: 47500
      name: p47500

