apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc-gg
spec:
  volumeName: host-pv-gg
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 1Gi
